"use client";
import { useMemo, useState } from "react";
import Image from "next/image";
import { ArrowDownRight, ArrowRight, Compass, Search, Menu, X, Utensils } from "lucide-react";
import { dishes, categories, type Dish } from "@/lib/dishes";
import FoodMap from "@/components/food-map";

function DishCard({ dish }: { dish: Dish }) {
  return <article className="dish-card">
    <div className="dish-image-wrap">{dish.image ? <Image unoptimized className="dish-image" src={dish.image} alt={dish.name} width={900} height={700} sizes="(max-width: 700px) 50vw, (max-width: 1000px) 33vw, 30vw" onError={(event)=>{event.currentTarget.style.display="none";}}/> : <div className="dish-image-placeholder" role="img" aria-label={`Photo being verified for ${dish.name}`}><span>PHOTO BEING VERIFIED</span><strong>{dish.name}</strong></div>}<span className="dish-tag">{dish.category}</span>{dish.imageSource && <a className="dish-photo-credit" href={dish.imageSource} target="_blank" rel="noreferrer" aria-label={`Photo credit for ${dish.name}`}>{dish.imageCredit}</a>}</div>
    <div className="dish-card-content"><div className="dish-card-topline"><span>{dish.place}</span><span className="dish-number">{dish.number}</span></div><h3>{dish.name}</h3><p>{dish.description}</p><div className="dish-card-bottom"><span className="local-note">{dish.note}</span><span className="round-arrow"><ArrowDownRight size={16}/></span></div>
    {dish.restaurants?.length ? <div className="restaurant-list"><div className="restaurant-list-heading"><span className="eyebrow-line"/><span>ASA MAKATILAW</span></div>{dish.restaurants.map((spot) => <article className="restaurant-spot" key={spot.name}>
      {spot.image ? <Image unoptimized className="restaurant-spot-image" src={spot.image} alt={spot.name} width={500} height={350} sizes="(max-width: 700px) 80vw, 25vw" onError={(event)=>{event.currentTarget.style.display="none";}}/> : <div className="restaurant-spot-placeholder">VENUE PHOTO NOT VERIFIED</div>}
      <div className="restaurant-spot-body"><div className="restaurant-spot-title"><h4>{spot.name}</h4>{spot.rating && <span className="restaurant-rating">★ {spot.rating}</span>}</div><div className="restaurant-meta">{spot.type}{spot.price ? ` · ${spot.price}` : ""}</div><div className="restaurant-address">{spot.address}</div>{spot.hours && <div className="restaurant-hours">{spot.hours}</div>}<p>{spot.description}</p>{spot.sourceUrl && <a className="restaurant-map-link" href={spot.sourceUrl} target="_blank" rel="noreferrer">Check listing <ArrowRight size={13}/></a>}<a className="restaurant-map-link" href={spot.mapPlaceId ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(spot.mapSearch)}&query_place_id=${spot.mapPlaceId}` : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(spot.mapSearch)}`} target="_blank" rel="noreferrer">Tan-awa sa mapa <ArrowRight size={13}/></a></div>
    </article>)}</div> : null}
    </div>
  </article>;
}
export default function HomePage() {
 const [activeCategory,setActiveCategory]=useState("Tanang putahe"),[search,setSearch]=useState(""),[mobileMenuOpen,setMobileMenuOpen]=useState(false);
 const filteredDishes=useMemo(()=>{const q=search.trim().toLowerCase();return dishes.filter(d=>(activeCategory==="Tanang putahe"||d.category===activeCategory)&&(!q||[d.name,d.description,d.place,d.category].some(v=>v.toLowerCase().includes(q))));},[activeCategory,search]);
 return <main>
 <div className="announcement"><span className="announcement-dot"/> Gikan sa Sugbo, para sa imong lami nga adventure. <ArrowRight size={13}/></div>
 <header className="site-header"><a className="wordmark" href="#"><span className="wordmark-symbol">t.</span><span>TILAW<span className="wordmark-period">.</span></span></a><nav className={"desktop-nav "+(mobileMenuOpen?"nav-open":"")}><a href="#dishes" onClick={()=>setMobileMenuOpen(false)}>Mga putahe</a><a href="#stories" onClick={()=>setMobileMenuOpen(false)}>Mga istorya</a><a href="#places" onClick={()=>setMobileMenuOpen(false)}>Asa mokaon</a></nav><div className="header-actions"><a className="map-link" href="#places"><Compass size={15}/><span>Food map</span></a><button className="mobile-menu-button" onClick={()=>setMobileMenuOpen(!mobileMenuOpen)} aria-label="Toggle menu">{mobileMenuOpen?<X/>:<Menu/>}</button></div></header>
 <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line"/> USA KA LAMIAN NGA PANAW</div><h1>Ang lami<br/>sa <em>Sugbo.</em></h1><p className="hero-description">Mga putahe, mga tawo, ug mga istorya nga naghatag og lami sa atong isla.</p><div className="hero-buttons"><a href="#dishes" className="button-primary">Tilawi ang Sugbo <ArrowRight size={16}/></a><a href="#stories" className="button-text">Atong mga istorya <ArrowDownRight size={16}/></a></div><div className="hero-footnote"><span className="footnote-icon"><Utensils size={15}/></span><span><strong>Gihimo uban sa gugma.</strong><br/>Para sa mga mahigugmaon sa pagkaon.</span></div></div><div className="hero-visual"><div className="hero-photo-main"><Image unoptimized src="https://upload.wikimedia.org/wikipedia/commons/2/26/Lechon_sa_Cebu.jpg" alt="Cebu lechon, a whole roasted pig with crisp skin" width={1300} height={1000} sizes="(max-width: 700px) 90vw, 45vw" priority/></div><div className="photo-caption"><span className="caption-kicker">ANG ATONG GARBO</span><span className="caption-title">Lami nga<br/>naay gigikanan.</span><span className="caption-index">01 / 04</span></div><div className="hero-stamp"><span>KAON</span><span className="stamp-star">✳</span><span>HIGUGMA</span><span className="stamp-star">✳</span><span>SUGBO</span></div><div className="hero-floating-note"><span className="floating-note-icon"><Compass size={16}/></span><span>Pagdiskobre sa<br/><strong>lami sa atong lugar</strong></span></div></div><div className="hero-bottom-label"><span>10° 18′ N</span><span className="label-line"/><span>123° 54′ E</span><span className="label-spacer"/><span>CEBU, PHILIPPINES</span></div></section>
 <section className="intro-strip"><p>DILI LANG PAGKAON.</p><h2>Kultura nga <em>matilawan.</em></h2><p className="intro-copy">Sa matag luto, adunay handumanan. Sa matag lamisa, adunay istorya. Atong ilhon ang mga lami nga nahimong bahin sa atong pagka-Cebuano.</p><span className="intro-decoration">✳</span></section>
 <section className="dishes-section section-pad" id="dishes"><div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> MGA PABORITO SA SUGBO</div><h2>Unsa may <em>lami?</em></h2></div><p>Gikan sa atong paboritong pagkaon sa kadalanan hangtod sa mga putahe nga atong gisaulog.</p></div><div className="dish-controls"><div className="category-tabs">{categories.map(c=><button key={c} className={activeCategory===c?"category-tab active":"category-tab"} onClick={()=>setActiveCategory(c)}>{c}</button>)}</div><label className="search-box"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pangitaa ang putahe..." aria-label="Search dishes"/>{search&&<button onClick={()=>setSearch("")} aria-label="Clear search"><X size={14}/></button>}</label></div><div className="dish-grid">{filteredDishes.map(d=><DishCard key={d.id} dish={d}/>)}</div>{!filteredDishes.length&&<div className="empty-state"><Search size={24}/><h3>Walay nakit-an nga putahe.</h3><p>Sulayi ang laing pulong o kategoriya.</p><button className="button-primary" onClick={()=>{setSearch("");setActiveCategory("Tanang putahe");}}>Ipakita tanan</button></div>}<div className="section-footer"><span>NAGLAMI NGA MGA PANGHUNA-HUNA</span><span>{String(filteredDishes.length).padStart(2,"0")} KA PANGITAAN</span></div></section>
 <section className="story-section" id="stories"><div className="story-image"><Image unoptimized src="https://upload.wikimedia.org/wikipedia/commons/2/26/Lechon_Cebu_%28whole%29_in_MCIA%2C_Cebu.jpg" alt="High-resolution whole Cebu lechon with golden, crispy roasted skin at Mactan-Cebu International Airport" width={1200} height={900} sizes="(max-width: 700px) 100vw, 50vw"/><div className="story-image-label"><span>SA LIKOD SA MATAG LUTO</span><span>✳</span></div></div><div className="story-copy"><div className="eyebrow"><span className="eyebrow-line"/> DILI MALIMTAN NGA MGA ISTORYA</div><h2>Ang lami,<br/>adunay <em>istorya.</em></h2><p>Ang atong pagkaon dili lang bahin sa sangkap o resipe. Bahin kini sa pamilya, tradisyon, ug mga tawo nga nagpadayon sa atong kultura.</p><a href="#newsletter" className="button-primary">Basaha ang mga istorya <ArrowRight size={16}/></a><div className="story-quote"><span>“</span><p>Ang pagkaon nga atong gipaambit, mao ang mga handumanan nga atong gitipigan.</p></div></div></section>
 <section className="places-section section-pad" id="places"><div className="places-top"><div><div className="eyebrow"><span className="eyebrow-line"/> ASA TA MOKAON?</div><h2>Sunod nimong <em>tilaw.</em></h2></div><p>Ang sunod nga lamian nga pangita mahimong anaa ra sa pikas kanto.</p></div><p className="map-intro">Pilia ang pin aron mahibal-an ang pagkaon nga nailhan sa lugar, ang istorya niini, ug asa magsugod sa imong food trip.</p><FoodMap/></section>
 <section className="newsletter-section" id="newsletter"><div className="newsletter-mark">t.</div><div className="newsletter-content"><div className="eyebrow"><span className="eyebrow-line"/> MAGKITA TA SA LAMISA</div><h2>Ayaw palabya ang <em>lami.</em></h2><p>Mga bag-ong putahe, lokal nga istorya, ug mga ideya para sa imong sunod nga food trip.</p></div><a className="button-light" href="mailto:hello@tilaw.ph?subject=Keep%20me%20updated%20about%20TILAW">I-update ko <ArrowRight size={16}/></a></section>
 <footer className="site-footer"><a className="wordmark footer-wordmark" href="#"><span className="wordmark-symbol">t.</span><span>TILAW<span className="wordmark-period">.</span></span></a><p>Gikan sa Sugbo, uban sa gugma.</p><div className="footer-links"><a href="#dishes">Mga putahe</a><a href="#stories">Mga istorya</a><a href="#places">Mga lugar</a></div><span className="copyright">© 2026 TILAW. GIHIMO SA SUGBO.</span></footer>
 </main>;
}